#### Taking campground data and adding 4 new rows for each campground then cleaning up

##### Edited: April 09, 2021

In [14]:
cd maps/Distance_calc/

C:\Users\alexp\OneDrive - University of New Brunswick\Grad Studies\Modelling_transport_pathways\maps\Distance_calc

In [15]:

#Importing packages for analysis
import pandas as pd

In [16]:
#Import distance table and route table to
campground_df=pd.read_csv('campground_clean.csv')

In [17]:
campground_df

,OID,Tye_of_Cam,Name,Province,Sites,Lat,Long,Aquiring_f,Notes,Phone_Numb,URL_
0,0.0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,47.428550,-66.909284,Purchase,"No free available firewood; lakeside, overnigh...",(506) 235-0793,https://www.parcsnbparks.info/en/parks/mount-c...
1,1.0,Provincial Park,Headwaters - Mount Carleton Provincial Park,NB,4,47.367365,-66.874482,-,"no fires allowed, proper hike-in (people make ...",(506) 235-0793,https://www.parcsnbparks.info/en/parks/mount-c...
2,2.0,Provincial Park,Franquelin - Mount Carleton Provincial Park,NB,9,47.425847,-66.904360,Purchase,"Hike-In, Little to no information on this camp...",(506) 235-0793,https://www.parcsnbparks.info/en/parks/mount-c...
3,3.0,Provincial Park,Williams Brook- Mount Carleton Provincial Park,NB,8,47.424917,-66.888382,-,"Hike-In, No fires (people still have fires bu...",(506) 235-0793,http://friendsofmountcarleton.ca/about-mount-c...
4,4.0,Local (City Park),Blue Heron Town Park,NB,146,48.016475,-66.369189,Purchase,"included are fully serviced sites, but many ot...",(506) 684-7860,http://www.campingheronbleu.com/
...,...,...,...,...,...,...,...,...,...,...,...
245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#Drop last rows
campground_df=campground_df.drop([231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249], axis=0)

In [19]:
campground_df.to_csv('Campground_cleand.csv')

In [ ]:
## Copying and adding 4 new rows to each existing row
campground_df=campground_df.append([campground_df]*4)

In [297]:
#Organize values so that all 4 copied rows are at the same place
campground_df=campground_df.sort_values(by=['OID'],ascending=True)

In [298]:
#add 4 new columns 
campground_df.insert(11,'CODE',0)
campground_df.insert(12,'Origin',0)
campground_df.insert(13,'lat',0)
campground_df.insert(14,'long',0)

In [302]:
#change the type of column OID from float64 to Object(String)
campground_df=campground_df.astype({'OID':'object'})

In [303]:
#Check to see how changes affect the dataframe
campground_df.tail(15)

,OID,Tye_of_Cam,Name,Province,Sites,Lat,Long,Aquiring_f,Notes,Phone_Numb,URL_,CODE,Origin,lat,long
228,228,KOA,Borden / Summerside KOA,PE,96,46.254707,-63.679565,Purchase,"87 serviced 9 unserviced, 5 cabins not include...",902-855-3492,https://koa.com/campgrounds/borden/,0,0,0,0
228,228,KOA,Borden / Summerside KOA,PE,96,46.254707,-63.679565,Purchase,"87 serviced 9 unserviced, 5 cabins not include...",902-855-3492,https://koa.com/campgrounds/borden/,0,0,0,0
228,228,KOA,Borden / Summerside KOA,PE,96,46.254707,-63.679565,Purchase,"87 serviced 9 unserviced, 5 cabins not include...",902-855-3492,https://koa.com/campgrounds/borden/,0,0,0,0
228,228,KOA,Borden / Summerside KOA,PE,96,46.254707,-63.679565,Purchase,"87 serviced 9 unserviced, 5 cabins not include...",902-855-3492,https://koa.com/campgrounds/borden/,0,0,0,0
228,228,KOA,Borden / Summerside KOA,PE,96,46.254707,-63.679565,Purchase,"87 serviced 9 unserviced, 5 cabins not include...",902-855-3492,https://koa.com/campgrounds/borden/,0,0,0,0
229,229,KOA,Cavendish KOA,PE,234,46.479595,-63.391471,Purchase,"all sites serviced, 12 serviced tenting sites ...",(902) 963-2079,https://koa.com/campgrounds/cavendish/,0,0,0,0
229,229,KOA,Cavendish KOA,PE,234,46.479595,-63.391471,Purchase,"all sites serviced, 12 serviced tenting sites ...",(902) 963-2079,https://koa.com/campgrounds/cavendish/,0,0,0,0
229,229,KOA,Cavendish KOA,PE,234,46.479595,-63.391471,Purchase,"all sites serviced, 12 serviced tenting sites ...",(902) 963-2079,https://koa.com/campgrounds/cavendish/,0,0,0,0
229,229,KOA,Cavendish KOA,PE,234,46.479595,-63.391471,Purchase,"all sites serviced, 12 serviced tenting sites ...",(902) 963-2079,https://koa.com/campgrounds/cavendish/,0,0,0,0
229,229,KOA,Cavendish KOA,PE,234,46.479595,-63.391471,Purchase,"all sites serviced, 12 serviced tenting sites ...",(902) 963-2079,https://koa.com/campgrounds/cavendish/,0,0,0,0
230,230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,0,0,0,0
230,230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,0,0,0,0
230,230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,0,0,0,0
230,230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,0,0,0,0
230,230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,0,0,0,0

In [304]:
#Add data to CODE column 
    #Add C + the OID value and  O + an ascending value of 1-5 for each set of campground  
Code=[]
Origin=0
for index,row in campground_df.iterrows():
    if Origin<5:
        Origin=Origin+1
    else:
        Origin=1
    Code.append('C'+ str(int(row['OID']))+'O'+str(Origin))
campground_df['CODE']=Code

In [305]:
# Create a new column for with only the origin using the last two values of the origin code
Origin_code=campground_df['CODE'].str[-2:]
campground_df['Origin_code']=Origin_code

In [306]:
#Insert data into each column by specified Origin codeto add data from Origin location + GPS coordinates 
Origin=[]
Lat=[]
Long=[]
for index,row in campground_df.iterrows():
    if row['Origin_code'] == 'O1':
        city='Edmunston'
        lat=47.363138271024624
        long=-68.32607675625937
    elif row['Origin_code'] == 'O2':
        city='Bedford'
        lat=44.649481728336255 
        long=-63.575298068542146
    elif row['Origin_code'] == 'O3':
        city='Oromocto'
        lat=45.8412673684528
        long=-66.508238007871
    elif row['Origin_code'] == 'O4':
        city='Moncton'
        lat=46.08971442081271
        long=-64.7753305171323
    elif row['Origin_code'] == 'O5':
        city='Fredericton'
        lat=45.96360737172908
        long=-66.64307843615934
    Origin.append(city)
    Lat.append(lat)
    Long.append(long)
campground_df['Origin']=Origin
campground_df['lat']=Lat
campground_df['long']=Long

In [307]:
#Remove OID and Origin_code columns because no longer necessary
campground_df=campground_df.drop(['Origin_code','OID'],axis=1)

In [308]:
#Rename columns to be more readable
campground_df=campground_df.rename(columns={'Lat':'C_Lat','Name':'Campground','Long':'C_Long','lat':'O_Lat','long':'O_Long','Tye_of_Cam':'Camp_type','Aquiring_f':'Firewood'})

In [309]:
#C-c-c-c-heck it out! 
campground_df

,Camp_type,Campground,Province,Sites,C_Lat,C_Long,Firewood,Notes,Phone_Numb,URL_,CODE,Origin,O_Lat,O_Long
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,47.428550,-66.909284,Purchase,"No free available firewood; lakeside, overnigh...",(506) 235-0793,https://www.parcsnbparks.info/en/parks/mount-c...,C0O1,Edmunston,47.363138,-68.326077
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,47.428550,-66.909284,Purchase,"No free available firewood; lakeside, overnigh...",(506) 235-0793,https://www.parcsnbparks.info/en/parks/mount-c...,C0O2,Bedford,44.649482,-63.575298
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,47.428550,-66.909284,Purchase,"No free available firewood; lakeside, overnigh...",(506) 235-0793,https://www.parcsnbparks.info/en/parks/mount-c...,C0O3,Oromocto,45.841267,-66.508238
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,47.428550,-66.909284,Purchase,"No free available firewood; lakeside, overnigh...",(506) 235-0793,https://www.parcsnbparks.info/en/parks/mount-c...,C0O4,Moncton,46.089714,-64.775331
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,47.428550,-66.909284,Purchase,"No free available firewood; lakeside, overnigh...",(506) 235-0793,https://www.parcsnbparks.info/en/parks/mount-c...,C0O5,Fredericton,45.963607,-66.643078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,C230O1,Edmunston,47.363138,-68.326077
230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,C230O2,Bedford,44.649482,-63.575298
230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,C230O3,Oromocto,45.841267,-66.508238
230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,C230O4,Moncton,46.089714,-64.775331
230,KOA,Cornwall / Charlottetown KOA,PE,272,46.213452,-63.187483,Purchase,"26 unserviced, 7 cabins not included (overnigh...",(902) 566-2421,https://koa.com/campgrounds/cornwall/,C230O5,Fredericton,45.963607,-66.643078

In [310]:
#reorder columns
campground_df= campground_df[['Camp_type', 'Campground','Province', 'Sites','Origin', 'CODE', 'C_Lat','C_Long','O_Lat','O_Long','Firewood', 'Notes','URL_']]

In [311]:
#C-c-c-c-heck it out! 
campground_df

,Camp_type,Campground,Province,Sites,Origin,CODE,C_Lat,C_Long,O_Lat,O_Long,Firewood,Notes,URL_
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Edmunston,C0O1,47.428550,-66.909284,47.363138,-68.326077,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Bedford,C0O2,47.428550,-66.909284,44.649482,-63.575298,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Oromocto,C0O3,47.428550,-66.909284,45.841267,-66.508238,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Moncton,C0O4,47.428550,-66.909284,46.089714,-64.775331,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Fredericton,C0O5,47.428550,-66.909284,45.963607,-66.643078,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,KOA,Cornwall / Charlottetown KOA,PE,272,Edmunston,C230O1,46.213452,-63.187483,47.363138,-68.326077,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/
230,KOA,Cornwall / Charlottetown KOA,PE,272,Bedford,C230O2,46.213452,-63.187483,44.649482,-63.575298,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/
230,KOA,Cornwall / Charlottetown KOA,PE,272,Oromocto,C230O3,46.213452,-63.187483,45.841267,-66.508238,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/
230,KOA,Cornwall / Charlottetown KOA,PE,272,Moncton,C230O4,46.213452,-63.187483,46.089714,-64.775331,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/
230,KOA,Cornwall / Charlottetown KOA,PE,272,Fredericton,C230O5,46.213452,-63.187483,45.963607,-66.643078,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/

In [312]:
#export data to Comma seperated value data sheet
campground_df.to_csv('Campground_Origin_Cleand.csv')