In [2]:
import pandas as pd
import os


os.chdir("/..")
os.chdir("Users/alexp/OneDrive - University of New Brunswick/Grad Studies/Modelling_transport_pathways/Clean_data_sets")
print("Directory changed")

Directory changed

In [3]:
#import CSV into a dataframe for distance and cleaned campground data
Route_distance_df=pd.read_csv('Route_distance_calc.csv')
Campground_df=pd.read_csv('Campground_Origin_Cleand.csv',index_col=0)
Campground_df.head(1)

,Camp_type,Campground,Province,Sites,Origin,CODE,C_Lat,C_Long,O_Lat,O_Long,Firewood,Notes,URL_
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Edmunston,C0O1,47.42855,-66.909284,47.363138,-68.326077,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...

In [4]:
Route_distance_df

       OID  ObjectID   Name  FirstStopI  LastStopID  StopCount  Total_Leng
0        0         1   C0O1           1        1156          2  146.320630
1        1         2   C0O2           2        1157          2  536.463229
2        2         3   C0O3           3        1158          2  254.183091
3        3         4   C0O4           4        1159          2  285.810976
4        4         5   C0O5           5        1160          2  235.126584
...    ...       ...    ...         ...         ...        ...         ...
1120  1120      1121  C99O1         496        1651          2  469.283086
1121  1121      1122  C99O2         497        1652          2  251.498910
1122  1122      1123  C99O3         498        1653          2  205.478419
1123  1123      1124  C99O4         499        1654          2  269.613474
1124  1124      1125  C99O5         500        1655          2  224.530174

[1125 rows x 7 columns]

In [5]:
#combine data from campground data with distance in km from origin to campground 
Camp_dist_df=pd.merge(left=Campground_df, right=Route_distance_df, left_on='CODE',right_on='Name')

In [6]:
#remove unnecessary columns and rename
Camp_dist_df=Camp_dist_df.drop(columns=['OID','ObjectID','Name','FirstStopI','LastStopID','StopCount'],axis=1)
Camp_dist_df=Camp_dist_df.rename(columns={'Total_Leng':'Distance_Km'})
Camp_dist_df.head(1)

,Camp_type,Campground,Province,Sites,Origin,CODE,C_Lat,C_Long,O_Lat,O_Long,Firewood,Notes,URL_,Distance_Km
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Edmunston,C0O1,47.42855,-66.909284,47.363138,-68.326077,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...,146.32063

In [7]:
#write to csv file in OneDrive - University of New Brunswick/Grad Studies/Modelling_transport_pathways/Clean_data_sets
Camp_dist_df.to_csv('Campground_Dist_Clean.csv')

In [8]:
#Insert a new column with population data from each origin location
Camp_dist_df.insert(14,'Population',0)
Population=[]
for index,row in Camp_dist_df.iterrows():
    if row['Origin'] == 'Edmunston':
        population='12086'
    elif row['Origin'] == 'Bedford':
        population='403131'
    elif row['Origin'] == 'Oromocto':
        population='9223'
    elif row['Origin'] == 'Moncton':
        population='71889'
    elif row['Origin'] == 'Fredericton':
        population='58220'
    Population.append(population)
Camp_dist_df['Population']=Population

In [9]:
#Remove any values that don't include real numbers to simplify(this can be removed when the campground data sheet is cleaned up)
import numpy as np
Camp_dist_df=Camp_dist_df.replace('?',np.NaN)
Camp_dist_df=Camp_dist_df.replace(r'^\s*$',np.NaN,regex=True)
Camp_dist_df=Camp_dist_df.replace('>50',np.NaN)
Camp_dist_df=Camp_dist_df.replace('>45',np.NaN)
Camp_dist_df=Camp_dist_df.replace('>60',np.NaN)

In [10]:
#Fill NAN sites to have zero 
Camp_dist_df['Sites'] = Camp_dist_df['Sites'].fillna(0)
Camp_dist_df

,Camp_type,Campground,Province,Sites,Origin,CODE,C_Lat,C_Long,O_Lat,O_Long,Firewood,Notes,URL_,Distance_Km,Population
0,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Edmunston,C0O1,47.428550,-66.909284,47.363138,-68.326077,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...,146.320630,12086
1,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Bedford,C0O2,47.428550,-66.909284,44.649482,-63.575298,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...,536.463229,403131
2,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Oromocto,C0O3,47.428550,-66.909284,45.841267,-66.508238,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...,254.183091,9223
3,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Moncton,C0O4,47.428550,-66.909284,46.089714,-64.775331,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...,285.810976,71889
4,Provincial Park,Armstrong Brook-Mount Carleton Provincial Park,NB,88,Fredericton,C0O5,47.428550,-66.909284,45.963607,-66.643078,Purchase,"No free available firewood; lakeside, overnigh...",https://www.parcsnbparks.info/en/parks/mount-c...,235.126584,58220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1120,KOA,Cornwall / Charlottetown KOA,PE,272,Edmunston,C230O1,46.213452,-63.187483,47.363138,-68.326077,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/,514.907422,12086
1121,KOA,Cornwall / Charlottetown KOA,PE,272,Bedford,C230O2,46.213452,-63.187483,44.649482,-63.575298,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/,296.669753,403131
1122,KOA,Cornwall / Charlottetown KOA,PE,272,Oromocto,C230O3,46.213452,-63.187483,45.841267,-66.508238,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/,304.347936,9223
1123,KOA,Cornwall / Charlottetown KOA,PE,272,Moncton,C230O4,46.213452,-63.187483,46.089714,-64.775331,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/,150.921133,71889
1124,KOA,Cornwall / Charlottetown KOA,PE,272,Fredericton,C230O5,46.213452,-63.187483,45.963607,-66.643078,Purchase,"26 unserviced, 7 cabins not included (overnigh...",https://koa.com/campgrounds/cornwall/,318.995531,58220

In [11]:
Camp_dist_df=Camp_dist_df.astype({'Sites':'float64'})

In [12]:
Camp_dist_df.dtypes

Camp_type       object
Campground      object
Province        object
Sites          float64
Origin          object
CODE            object
C_Lat          float64
C_Long         float64
O_Lat          float64
O_Long         float64
Firewood        object
Notes           object
URL_            object
Distance_Km    float64
Population      object
dtype: object

In [13]:
Camp_dist_piv_df=Camp_dist_df.pivot(index='Campground', columns='Origin', values=['Distance_Km','Sites','Population'])

In [14]:
#import numpy as np
#Camp_dist_piv_df=Camp_dist_piv_df.replace('?',np.NaN)
#Camp_dist_piv_df=Camp_dist_piv_df.replace(r'^\s*$',np.NaN,regex=True)
#Camp_dist_piv_df

In [15]:
Camp_dist_piv_df.astype({'Sites':'float64'},{'Distance_Km':'float64'})

                                               Distance_Km            \
Origin                                             Bedford Edmunston
Campground
ADDA Fundy Tides CG- City                          224.441   521.344
Adventures East Campground & Cottages              332.706    761.17
All Done Camping                                   313.666   352.895
All Points East Campground                         392.958   611.195
Amherst Shore Provincial Park                      191.456   459.083
...                                                    ...       ...
Whycocomagh Provincial Park                        305.822   734.285
Williams Brook- Mount Carleton Provincial Park     539.104   148.961
Winter Bay Tent & Trailer Park                      314.48   532.718
Woolastook Park Campground                         415.783   238.804
Yogi Bear's Jellystone Park Camping Resort         140.023   516.124

                                                                              \
Origin                                         Fredericton  Moncton Oromocto
Campground
ADDA Fundy Tides CG- City                          315.646  146.749  300.998
Adventures East Campground & Cottages              555.472  386.575  540.824
All Done Camping                                   121.224  62.8908  106.538
All Points East Campground                         415.283  247.209  400.636
Amherst Shore Provincial Park                      257.006  88.1085  242.358
...                                                    ...      ...      ...
Whycocomagh Provincial Park                        528.588   359.69   513.94
Williams Brook- Mount Carleton Provincial Park     237.767  288.452  256.824
Winter Bay Tent & Trailer Park                     336.806  168.731  322.158
Woolastook Park Campground                         24.6768  190.214  37.0834
Yogi Bear's Jellystone Park Camping Resort         271.371  316.454  252.319

                                                 Sites                        \
Origin                                         Bedford Edmunston Fredericton
Campground
ADDA Fundy Tides CG- City                           35        35          35
Adventures East Campground & Cottages               85        85          85
All Done Camping                                    46        46          46
All Points East Campground                          40        40          40
Amherst Shore Provincial Park                       42        42          42
...                                                ...       ...         ...
Whycocomagh Provincial Park                         33        33          33
Williams Brook- Mount Carleton Provincial Park       8         8           8
Winter Bay Tent & Trailer Park                       0         0           0
Woolastook Park Campground                           0         0           0
Yogi Bear's Jellystone Park Camping Resort         199       199         199

                                                                Population  \
Origin                                         Moncton Oromocto    Bedford
Campground
ADDA Fundy Tides CG- City                           35       35     403131
Adventures East Campground & Cottages               85       85     403131
All Done Camping                                    46       46     403131
All Points East Campground                          40       40     403131
Amherst Shore Provincial Park                       42       42     403131
...                                                ...      ...        ...
Whycocomagh Provincial Park                         33       33     403131
Williams Brook- Mount Carleton Provincial Park       8        8     403131
Winter Bay Tent & Trailer Park                       0        0     403131
Woolastook Park Campground                           0        0     403131
Yogi Bear's Jellystone Park Camping Resort         199      199     403131

                                                                              \
Origin                                         Edmunston Fredericton Moncton
Campground
ADDA Fundy Tides CG- City                          12086       58220   71889
Adventures East Campground & Cottages              12086       58220   71889
All Done Camping                                   12086       58220   71889
All Points East Campground                         12086       58220   71889
Amherst Shore Provincial Park                      12086       58220   71889
...                                                  ...         ...     ...
Whycocomagh Provincial Park                        12086       58220   71889
Williams Brook- Mount Carleton Provincial Park     12086       58220   71889
Winter Bay Tent & Trailer Park                     12086       58220   71889
Woolastook Park Campground                         12086       58220   71889
Yogi Bear's Jellystone Park Camping Resort         12086       58220   71889


Origin                                         Oromocto
Campground
ADDA Fundy Tides CG- City                          9223
Adventures East Campground & Cottages              9223
All Done Camping                                   9223
All Points East Campground                         9223
Amherst Shore Provincial Park                      9223
...                                                 ...
Whycocomagh Provincial Park                        9223
Williams Brook- Mount Carleton Provincial Park     9223
Winter Bay Tent & Trailer Park                     9223
Woolastook Park Campground                         9223
Yogi Bear's Jellystone Park Camping Resort         9223

[225 rows x 15 columns]

In [16]:
Camp_dist_piv_df.dtypes

             Origin
Distance_Km  Bedford        object
             Edmunston      object
             Fredericton    object
             Moncton        object
             Oromocto       object
Sites        Bedford        object
             Edmunston      object
             Fredericton    object
             Moncton        object
             Oromocto       object
Population   Bedford        object
             Edmunston      object
             Fredericton    object
             Moncton        object
             Oromocto       object
dtype: object

In [17]:
Camp_dist_piv_df.to_csv('Campground_Dist_Pop_Sites_matrix.csv')

In [27]:
df=Camp_dist_piv_df.stack().reset_index()
df

,Campground,Origin,Distance_Km,Sites,Population
0,ADDA Fundy Tides CG- City,Bedford,224.441,35,403131
1,ADDA Fundy Tides CG- City,Edmunston,521.344,35,12086
2,ADDA Fundy Tides CG- City,Fredericton,315.646,35,58220
3,ADDA Fundy Tides CG- City,Moncton,146.749,35,71889
4,ADDA Fundy Tides CG- City,Oromocto,300.998,35,9223
...,...,...,...,...,...
1120,Yogi Bear's Jellystone Park Camping Resort,Bedford,140.023,199,403131
1121,Yogi Bear's Jellystone Park Camping Resort,Edmunston,516.124,199,12086
1122,Yogi Bear's Jellystone Park Camping Resort,Fredericton,271.371,199,58220
1123,Yogi Bear's Jellystone Park Camping Resort,Moncton,316.454,199,71889
1124,Yogi Bear's Jellystone Park Camping Resort,Oromocto,252.319,199,9223

In [29]:
df.to_csv('Campground_origin_data_raw.csv')