In [7]:
cd ..\

C:\Users\alexp\OneDrive - University of New Brunswick\Grad Studies\Modelling_transport_pathways

In [8]:
import pandas as pd

In [10]:
Pop_df = pd.read_csv('Clean_data_sets/US_city_pop_clean.csv',index_col=[0])
Reserv_df = pd.read_csv('Clean_data_sets/Reservation_by_city_all_2020.csv',index_col=[0])

In [11]:
Pop_df

                          Name   STNAME  POPESTIMATE2019
0                      Alabama  Alabama          4903185
1                    Abbeville  Alabama             2560
2                   Adamsville  Alabama             4281
3                      Addison  Alabama              718
4                        Akron  Alabama              328
...                        ...      ...              ...
81425     Balance of Uinta Cou  Wyoming             4783
81426             Washakie Cou  Wyoming             7805
81429  Balance of Washakie Cou  Wyoming             2531
81430               Weston Cou  Wyoming             6927
81433    Balance of Weston Cou  Wyoming             2474

[43796 rows x 3 columns]

In [12]:
Reserv_df

               city           state  #_of_reservations
0         Abbeville         Alabama                  1
1         Abbeville       Louisiana                  2
2         Abbeville     Mississippi                  2
3         Abbeville  South Carolina                  1
4             Abbot           Maine                  1
...             ...             ...                ...
11375    Zion Grove    Pennsylvania                  1
11376    Zionsville         Indiana                 34
11377      Zirconia  North Carolina                  1
11378  Zumbro Falls       Minnesota                  8
11379      Zumbrota       Minnesota                  2

[11380 rows x 3 columns]

In [14]:
Merge_df = pd.merge(Pop_df,Reserv_df,how='right',left_on=['STNAME','Name'], right_on=['state','city'])

In [15]:
Merge_df = Merge_df[['city','STNAME', 'POPESTIMATE2019','#_of_reservations']]

In [16]:
Merge_df

               city          STNAME  POPESTIMATE2019  #_of_reservations
0         Abbeville         Alabama           2560.0                  1
1         Abbeville       Louisiana          12038.0                  2
2         Abbeville     Mississippi            423.0                  2
3         Abbeville  South Carolina           5014.0                  1
4             Abbot           Maine            677.0                  1
...             ...             ...              ...                ...
11375    Zion Grove             NaN              NaN                  1
11376    Zionsville         Indiana          28357.0                 34
11377      Zirconia             NaN              NaN                  1
11378  Zumbro Falls       Minnesota            239.0                  8
11379      Zumbrota       Minnesota           3501.0                  2

[11380 rows x 4 columns]

In [18]:
Merge_df.to_csv('Merged_pop_reserv_all.csv')

In [25]:
Reserv_df.loc[Reserv_df['city'] == 'Adamsville']

          city         state  #_of_reservations
45  Adamsville  Pennsylvania                  1
46  Adamsville  Rhode Island                  1