In [83]:
cd Modelling_transport_pathways

[WinError 2] The system cannot find the file specified: 'Modelling_transport_pathways'
C:\Users\alexp\OneDrive - University of New Brunswick\Grad Studies\Modelling_transport_pathways

In [84]:
import pandas as pd

In [85]:
Pop_df=pd.read_csv('Clean_data_sets/US_city_pop_clean.csv',index_col=[0])
Reserv_df=pd.read_csv('Clean_data_sets/Maine_reservations_by_city.csv',index_col=[0])

In [86]:
Pop_df

                          Name   STNAME  POPESTIMATE2019
0                      Alabama  Alabama          4903185
1                    Abbeville  Alabama             2560
2                   Adamsville  Alabama             4281
3                      Addison  Alabama              718
4                        Akron  Alabama              328
...                        ...      ...              ...
81425     Balance of Uinta Cou  Wyoming             4783
81426             Washakie Cou  Wyoming             7805
81429  Balance of Washakie Cou  Wyoming             2531
81430               Weston Cou  Wyoming             6927
81433    Balance of Weston Cou  Wyoming             2474

[43796 rows x 3 columns]

In [87]:
Pop_df.loc[Pop_df['Name'] == 'Albion']

         Name      STNAME  POPESTIMATE2019
7462   Albion       Idaho              276
7960   Albion    Illinois             1899
15322  Albion     Indiana             2373
19120  Albion        Iowa              490
27340  Albion       Maine             2094
28881  Albion    Michigan             8402
41965  Albion    Nebraska             1585
48591  Albion    New York             7982
59504  Albion    Oklahoma              100
75981  Albion  Washington              604
78394  Albion   Wisconsin             2093

In [88]:
Reserv_df

          city state  #_of_reservations  State
0        Abbot    ME                  1  Maine
1        Acton    ME                  1  Maine
2       Albion    ME                  4  Maine
3       Alfred    ME                  1  Maine
4         Alna    ME                  1  Maine
..         ...   ...                ...    ...
188   Winthrop    ME                  8  Maine
189  Wiscasset    ME                  2  Maine
190   Woolwich    ME                  1  Maine
191   Yarmouth    ME                 15  Maine
192       York    ME                  5  Maine

[193 rows x 4 columns]

In [89]:
Merge_df = pd.merge(Pop_df,Reserv_df,how='right',left_on=['STNAME','Name'], right_on=['State','city'])

In [90]:
Merge_df = Merge_df[['city','STNAME', 'POPESTIMATE2019','#_of_reservations']]

In [91]:
Merge_df

          city STNAME  POPESTIMATE2019  #_of_reservations
0        Abbot  Maine            677.0                  1
1        Acton  Maine           2621.0                  1
2       Albion  Maine           2094.0                  4
3       Alfred  Maine           3163.0                  1
4         Alna  Maine            734.0                  1
..         ...    ...              ...                ...
188   Winthrop  Maine           5993.0                  8
189  Wiscasset  Maine           3763.0                  2
190   Woolwich  Maine           3181.0                  1
191   Yarmouth  Maine           8589.0                 15
192       York  Maine          13290.0                  5

[193 rows x 4 columns]

In [92]:
Merge_df.to_csv('Merged_pop_reserv_data.csv')