In [6]:
cd ..\Dirty_data_sets

C:\Users\alexp\OneDrive - University of New Brunswick\Grad Studies\Modelling_transport_pathways\Dirty_data_sets

In [7]:
import pandas as pd

In [8]:
Reservation_df=pd.read_csv('FY20_Historical_Reservations_Full.csv')

C:\Users\alexp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (5,6,7,12,13,15,17,35) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [9]:
Reservation_df

,historicalreservationid,ordernumber,agency,orgid,codehierarchy,regioncode,regiondescription,parentlocationid,parentlocation,legacyfacilityid,...,totalbeforetax,discount,totalpaid,startdate,enddate,orderdate,nights,numberofpeople,equipmentdescription,equipmentlength
0,fa50401c-f08a-4738-b576-56335cc19cb7,0121072064-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2019-10-17 0:00,2019-10-18 0:00,25:42.3,1 day,6.0,NaN,0.0
1,09c37303-cf15-49d9-9b0c-ccc120328bbb,0200063847-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2020-04-11 0:00,2020-04-12 0:00,35:11.6,1 day,1.0,NaN,0.0
2,f1f5c841-46b1-4ff8-a6dc-fcac2e76ae1c,0200087454-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,83.0,0.0,83.0,2020-09-07 0:00,2020-09-10 0:00,19:08.2,3 days,2.0,NaN,0.0
3,619f4394-1cac-4a64-8f0c-eae6e7f6bf3b,0200102788-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2020-03-21 0:00,2020-03-22 0:00,01:33.9,1 day,3.0,NaN,0.0
4,82674243-7f31-41e6-b3db-d0690513cad3,0200147542-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,0.0,0.0,0.0,2019-12-07 0:00,2019-12-08 0:00,54:01.4,1 day,2.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,e9f6b2b9-a3b0-11ea-b556-6653b7d9f46e,0281991828-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,27.0,0.0,27.0,2020-06-05 0:00,2020-06-05 0:00,40:18.2,0:00:00,1.0,NaN,NaN
1048571,c51c645c-b250-11ea-a96c-8e3940941329,0281991863-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-06-19 0:00,2020-06-19 0:00,20:27.5,0:00:00,1.0,NaN,NaN
1048572,a87f5276-a0ec-11ea-94cc-3aca2611a872,0281991891-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-06-16 0:00,2020-06-16 0:00,09:05.7,0:00:00,1.0,NaN,NaN
1048573,5384e1dc-fd0c-11ea-b504-e2de83ef30d6,0281991986-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-09-30 0:00,2020-09-30 0:00,46:57.7,0:00:00,0.0,NaN,NaN
1048574,35c31b69-c84f-11ea-a856-2a7dac6c22ec,0281992247-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-08-07 0:00,2020-08-07 0:00,02:48.7,0:00:00,0.0,NaN,NaN

In [10]:
Reservation_df = Reservation_df.loc[Reservation_df['inventorytype'] == 'CAMPING'].dropna(subset=['customerstate']).loc[(Reservation_df.customerstate != 'AK') & (Reservation_df.customerstate !='HI') & (Reservation_df.customerstate !='AE') & (Reservation_df.customerstate !='PR') & (Reservation_df.customerstate !='AA') & (Reservation_df.customerstate !='VI') & (Reservation_df.customerstate !='AP')]
Reservation_df.to_csv('origin_state_all.csv')

In [11]:
print(Reservation_df.customerstate.unique())
Reservation_df.shape

['TX' 'CO' 'NH' 'NC' 'CA' 'AZ' 'VA' 'OR' 'ID' 'MT' 'MA' 'PA' 'FL' 'MN'
 'WA' 'NY' 'UT' 'MO' 'KS' 'SD' 'IA' 'NM' 'MI' 'NV' 'IL' 'GA' 'SC' 'WI'
 'WY' 'ND' 'OH' 'WV' 'KY' 'LA' 'MD' 'VT' 'NJ' 'IN' 'ME' 'TN' 'DC' 'CT'
 'AR' 'OK' 'NE' 'DE' 'RI' 'AL' 'MS']

(254122, 37)

In [12]:
Zip_code_list= Reservation_df['customerzip'].value_counts().index.tolist()

In [13]:
Zip_code=[]
for code in Zip_code_list:
    if len(code) == 4:
        zip_code='0'+ code
        Zip_code.append(zip_code)
    else:
        Zip_code.append(code)

In [14]:
for code in Zip_code:
    if len(code) < 5:
        print('Bad code')
    elif len (code) > 6:
        print('Bad Code')

In [15]:
Reservation_sum_df = Reservation_df['customerzip'].value_counts().rename_axis('zip').reset_index(name='counts')

In [16]:
Reservation_sum_list=[]
for zcode in Reservation_sum_df['zip']:
    if len(zcode) == 4:
        zip_code='0'+ zcode
        Reservation_sum_list.append(zip_code)
    else:
        Reservation_sum_list.append(zcode)
Reservation_sum_df['zip'] = Reservation_sum_list

In [17]:
for zcode in Reservation_sum_df['zip']:
    if len(zcode) < 5:
        print('Zip code to short')
        print(zcode)
    elif len (zcode) > 6:
        print('Zip code too long')

In [18]:
Zip_code_info=[]
import zipcodes
for x in Zip_code:
    Zip_code_info.append(zipcodes.matching(x))

In [19]:
flattened = [] 
for sublist in Zip_code_info: 
    for val in sublist: 
        flattened.append(val)

In [20]:
#convert to a dataframe
Zip_code_df = pd.DataFrame(flattened,columns=('zip_code','zip_code_type','active','city','acceptable_cities','unacceptable_cities','state','county','timezone','area_codes','world_region','country','lat','long'))

In [21]:
#drop non-important columns
Zip_code_df = Zip_code_df.drop(columns=['timezone','world_region','country'])
Zip_code_df

,zip_code,zip_code_type,active,city,acceptable_cities,unacceptable_cities,state,county,area_codes,lat,long
0,59602,STANDARD,True,Helena,[],[],MT,Lewis and Clark County,[406],46.6786,-111.9806
1,59718,STANDARD,True,Bozeman,[],[],MT,Gallatin County,[406],45.6580,-111.2035
2,80027,STANDARD,True,Louisville,[Superior],[],CO,Boulder County,[303],39.9570,-105.1578
3,59601,STANDARD,True,Helena,[],[],MT,Lewis and Clark County,[406],46.5290,-112.1225
4,80304,STANDARD,True,Boulder,[],[],CO,Boulder County,[303],40.0452,-105.2920
...,...,...,...,...,...,...,...,...,...,...,...
16105,17540,STANDARD,True,Leola,[],"[Bareville, Leacock, Oregon, Rockrimmin Ridge]",PA,Lancaster County,[717],40.1010,-76.1879
16106,25978,STANDARD,True,Nimitz,[],[],WV,Summers County,[304],37.6229,-80.9392
16107,62240,STANDARD,True,East Carondelet,[E Carondelet],[Imbs],IL,St. Clair County,[618],38.5288,-90.2047
16108,21843,PO BOX,True,Ocean City,[],[],MD,Worcester County,[410],38.3898,-75.0842
16109,54732,STANDARD,True,Cornell,[],[],WI,Chippewa County,[715],45.1257,-91.1996

In [22]:
State_extend=[]
for state in Zip_code_df['state']:
    if state == 'TX':
        name = 'Texas'
        State_extend.append(name)
    elif state == 'CO':
        name = 'Colorado'
        State_extend.append(name)
    elif state == 'NH':
        name = 'New Hampshire'
        State_extend.append(name)
    elif state == 'NC':
        name = 'North Carolina'
        State_extend.append(name)
    elif state == 'CA':
        name = 'California'
        State_extend.append(name)
    elif state == 'AZ':
        name = 'Arizona'
        State_extend.append(name)
    elif state == 'VA':
        name = 'Virginia'
        State_extend.append(name)
    elif state == 'OR':
        name = 'Oregon'
        State_extend.append(name)
    elif state == 'ID':
        name = 'Indiana'
        State_extend.append(name)
    elif state == 'MT':
        name = 'Montana'
        State_extend.append(name)
    elif state == 'MA':
        name = 'Massachusetts'
        State_extend.append(name)
    elif state == 'PA':
        name = 'Pennsylvania'
        State_extend.append(name)
    elif state == 'FL':
        name = 'Florida'
        State_extend.append(name)
    elif state == 'MN':
        name = 'Minnesota'
        State_extend.append(name)
    elif state == 'WA':
        name = 'Washington'
        State_extend.append(name)
    elif state == 'NY':
        name = 'New York'
        State_extend.append(name)
    elif state == 'UT':
        name = 'Utah'
        State_extend.append(name)
    elif state == 'MO':
        name = 'Montana'
        State_extend.append(name)
    elif state == 'KS':
        name = 'Kansas'
        State_extend.append(name)
    elif state == 'SD':
        name = 'South Dakota'
        State_extend.append(name)
    elif state == 'IA':
        name = 'Iowa'
        State_extend.append(name)
    elif state == 'NM':
        name = 'New Mexico'
        State_extend.append(name)
    elif state == 'MI':
        name = 'Michigan'
        State_extend.append(name)
    elif state == 'NV':
        name = 'Nevada'
        State_extend.append(name)
    elif state == 'IL':
        name = 'Illinois'
        State_extend.append(name)
    elif state == 'GA':
        name = 'Georgia'
        State_extend.append(name)
    elif state == 'SC':
        name = 'South Carolina'
        State_extend.append(name)
    elif state == 'WI':
        name = 'Wisconsin'
        State_extend.append(name)
    elif state == 'WY':
        name = 'Wyoming'
        State_extend.append(name)
    elif state == 'ND':
        name = 'North Dakota'
        State_extend.append(name)
    elif state == 'OH':
        name = 'Ohio'
        State_extend.append(name)
    elif state == 'WV':
        name = 'West Virginia'
        State_extend.append(name)
    elif state == 'KY':
        name = 'Kentucky'
        State_extend.append(name)
    elif state == 'LA':
        name = 'Louisiana'
        State_extend.append(name)
    elif state == 'MD':
        name = 'Maryland'
        State_extend.append(name)
    elif state == 'VT':
        name = 'Vermont'
        State_extend.append(name)
    elif state == 'NJ':
        name = 'New Jersey'
        State_extend.append(name)
    elif state == 'IN':
        name = 'Indiana'
        State_extend.append(name)
    elif state == 'ME':
        name = 'Maine'
        State_extend.append(name)
    elif state == 'TN':
        name = 'Tennessee'
        State_extend.append(name)
    elif state == 'DC':
        name = 'District of Columbia'
        State_extend.append(name)
    elif state == 'CT':
        name = 'Connecticut'
        State_extend.append(name)
    elif state == 'AR':
        name = 'Arkansas'
        State_extend.append(name)
    elif state == 'OK':
        name = 'Oklahoma'
        State_extend.append(name)
    elif state == 'NE':
        name = 'Nebraska'
        State_extend.append(name)
    elif state == 'DE':
        name = 'Delaware'
        State_extend.append(name)
    elif state == 'RI':
        name = 'Rhode Island'
        State_extend.append(name)
    elif state == 'AL':
        name = 'Alabama'
        State_extend.append(name)
    elif state == 'MS':
        name = 'Mississippi'
        State_extend.append(name)
Zip_code_df['state'] = State_extend

In [23]:
merge_df = pd.merge(left=Zip_code_df,right=Reservation_sum_df, left_on='zip_code',right_on='zip' )

In [24]:
merge_df = merge_df.rename(columns={'counts':'#_of_reservations'})

In [25]:
Reserv_num_group_df= merge_df.groupby(['city','state'], as_index=False)['#_of_reservations'].sum()
Reserv_num_group_df= Reserv_num_group_df.loc[Reserv_num_group_df['#_of_reservations'] > 5]

In [26]:
Reserv_num_group_df.sort_values(by='#_of_reservations')

                city                 state  #_of_reservations
8124       Pittstown            New Jersey                  6
8579            Rice             Minnesota                  6
2394        Crawford              Colorado                  6
2404   Crescent City            California                  6
2406       Cresskill            New Jersey                  6
...              ...                   ...                ...
1090         Boulder              Colorado               2465
9059       San Diego            California               3343
5928     Los Angeles            California               3410
10671     Washington  District of Columbia               3928
2686          Denver              Colorado               5798

[4737 rows x 3 columns]

In [28]:
Reserv_num_group_df.to_csv('Reservation_by_city_all_more_5_2020.csv')