In [5]:
cd ..\Dirty_data_sets

C:\Users\alexp\OneDrive - University of New Brunswick\Grad Studies\Modelling_transport_pathways\Dirty_data_sets

## Calculating the number of campsite reservations made in a city
### To do this I needed to:
#### 1. Clean the dataset to only include cities in the state of Maine
#### 2. Calculate the number of campground reservations made at each exclusive zip code
#### 3. Join all the zip codes to fit into a single city and sum the number of reservations

In [134]:
import pandas as pd

In [135]:
#importing the csv containing historical reservation data from the Unites States for the 2020 camping season(FY 2020), Website URL: https://ridb.recreation.gov/download
Reservation_df=pd.read_csv('FY20_Historical_Reservations_Full.csv')

C:\Users\alexp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (5,6,7,12,13,15,17,35) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [136]:
#print data
Reservation_df

,historicalreservationid,ordernumber,agency,orgid,codehierarchy,regioncode,regiondescription,parentlocationid,parentlocation,legacyfacilityid,...,totalbeforetax,discount,totalpaid,startdate,enddate,orderdate,nights,numberofpeople,equipmentdescription,equipmentlength
0,fa50401c-f08a-4738-b576-56335cc19cb7,0121072064-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2019-10-17 0:00,2019-10-18 0:00,25:42.3,1 day,6.0,NaN,0.0
1,09c37303-cf15-49d9-9b0c-ccc120328bbb,0200063847-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2020-04-11 0:00,2020-04-12 0:00,35:11.6,1 day,1.0,NaN,0.0
2,f1f5c841-46b1-4ff8-a6dc-fcac2e76ae1c,0200087454-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,83.0,0.0,83.0,2020-09-07 0:00,2020-09-10 0:00,19:08.2,3 days,2.0,NaN,0.0
3,619f4394-1cac-4a64-8f0c-eae6e7f6bf3b,0200102788-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2020-03-21 0:00,2020-03-22 0:00,01:33.9,1 day,3.0,NaN,0.0
4,82674243-7f31-41e6-b3db-d0690513cad3,0200147542-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,0.0,0.0,0.0,2019-12-07 0:00,2019-12-08 0:00,54:01.4,1 day,2.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,e9f6b2b9-a3b0-11ea-b556-6653b7d9f46e,0281991828-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,27.0,0.0,27.0,2020-06-05 0:00,2020-06-05 0:00,40:18.2,0:00:00,1.0,NaN,NaN
1048571,c51c645c-b250-11ea-a96c-8e3940941329,0281991863-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-06-19 0:00,2020-06-19 0:00,20:27.5,0:00:00,1.0,NaN,NaN
1048572,a87f5276-a0ec-11ea-94cc-3aca2611a872,0281991891-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-06-16 0:00,2020-06-16 0:00,09:05.7,0:00:00,1.0,NaN,NaN
1048573,5384e1dc-fd0c-11ea-b504-e2de83ef30d6,0281991986-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-09-30 0:00,2020-09-30 0:00,46:57.7,0:00:00,0.0,NaN,NaN
1048574,35c31b69-c84f-11ea-a856-2a7dac6c22ec,0281992247-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-08-07 0:00,2020-08-07 0:00,02:48.7,0:00:00,0.0,NaN,NaN

In [137]:
##Discontinued coding line went with people from origin location not destination location
#including only **camping** reservations from the state of Maine 
#Maine_df = Reservation_df.loc[Reservation_df['facilitystate'] == 'Maine'].loc[Reservation_df['inventorytype'] == 'CAMPING']
#Maine_df.to_csv('Maine_reservations.csv')

In [138]:
#Include only camping reservations from the origin State of Maine
Maine_origin_df = Reservation_df.loc[Reservation_df['customerstate'] == 'ME'].loc[Reservation_df['inventorytype'] == 'CAMPING']
Maine_origin_df.to_csv('origin_state.csv')

In [139]:
#Take the zip codes and convert them into a single list
test_df = Maine_origin_df['customerzip'].value_counts().index.tolist()

In [140]:
#add a '0' in front of each zip code so that it matches the format from zipcodes
Test_list=[]
for x in test_df:
    zip_code='0'+ x
    Test_list.append(zip_code)

In [141]:
#Summarize the number of campground reservations there were for a specific ZIP code.
sum_df = Maine_origin_df['customerzip'].value_counts().rename_axis('zip').reset_index(name='counts')

In [142]:
#add a '0' in front of each zip code so that it matches the format from zipcodes and change the dataframe column data to match the change
sum_list=[]
for x in sum_df['zip']:
    bingo= '0'+ x
    sum_list.append(bingo)
sum_df['zip']= sum_list

In [143]:
#add data from the reservation zip codes to add extra data like city, state, etc... 
Maine_test_zip=[]
import zipcodes
for x in Test_list:
    Maine_test_zip.append(zipcodes.matching(x))

In [144]:
#remove unnecessary square brackets outside of the dictionary: from: [[{dict1}],[{dict2}],[{dict3}]] to:[{dict1},{dict2},{dict3}]
flattened = [] 
for sublist in Maine_test_zip: 
    for val in sublist: 
        flattened.append(val)

In [145]:
#convert to a dataframe
df= pd.DataFrame(flattened,columns=('zip_code','zip_code_type','active','city','acceptable_cities','unacceptable_cities','state','county','timezone','area_codes','world_region','country','lat','long'))

In [146]:
#drop non-important columns
df.drop(columns=['timezone','world_region','country'])

,zip_code,zip_code_type,active,city,acceptable_cities,unacceptable_cities,state,county,area_codes,lat,long
0,04103,STANDARD,True,Portland,[],[],ME,Cumberland County,[207],43.6937,-70.2904
1,04011,STANDARD,True,Brunswick,"[Birch Island, Cundys Harbor, Mere Point]",[Nas Brunswick],ME,Cumberland County,[207],43.8931,-69.9723
2,04210,STANDARD,True,Auburn,[],[],ME,Androscoggin County,[207],44.0862,-70.2272
3,04107,STANDARD,True,Cape Elizabeth,"[Cape Cottage, Cape Eliz, Pond Cove, Portland]",[],ME,Cumberland County,[207],43.5933,-70.2387
4,04106,STANDARD,True,South Portland,"[Portland, S Portland]",[So Portland],ME,Cumberland County,[207],43.6263,-70.3007
...,...,...,...,...,...,...,...,...,...,...,...
206,04669,STANDARD,True,Prospect Harbor,[Prospect Hbr],[],ME,Hancock County,[207],44.4337,-68.0364
207,04030,STANDARD,True,East Waterboro,[E Waterboro],[],ME,York County,[207],43.5869,-70.7026
208,04937,STANDARD,True,Fairfield,[],[],ME,Somerset County,[207],44.6675,-69.6795
209,04342,STANDARD,True,Dresden,[],[],ME,Lincoln County,[207],44.0766,-69.7401
210,03902,STANDARD,True,Cape Neddick,[],[],ME,York County,[207],43.2225,-70.6402

In [147]:
#Merge zip code data(df) to the campground reservation counts(sum_df) 
merge_df=pd.merge(left=df, right=sum_df, left_on='zip_code', right_on='zip')

In [148]:
#remove any zip codes for businesses/large groups and for PO Boxes
merge_df = merge_df[merge_df.zip_code_type == 'STANDARD']

In [149]:
#Rename count column to better represent actual value: number of reservations
merge_df = merge_df.rename(columns={'counts':'#_of_reservations'})

In [150]:
merge_df

,zip_code,zip_code_type,active,city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,lat,long,zip,#_of_reservations
0,04103,STANDARD,True,Portland,[],[],ME,Cumberland County,America/New_York,[207],NA,US,43.6937,-70.2904,04103,50
1,04011,STANDARD,True,Brunswick,"[Birch Island, Cundys Harbor, Mere Point]",[Nas Brunswick],ME,Cumberland County,America/New_York,[207],NA,US,43.8931,-69.9723,04011,31
2,04210,STANDARD,True,Auburn,[],[],ME,Androscoggin County,America/New_York,[207],NA,US,44.0862,-70.2272,04210,30
3,04107,STANDARD,True,Cape Elizabeth,"[Cape Cottage, Cape Eliz, Pond Cove, Portland]",[],ME,Cumberland County,America/New_York,[207],NA,US,43.5933,-70.2387,04107,30
4,04106,STANDARD,True,South Portland,"[Portland, S Portland]",[So Portland],ME,Cumberland County,America/New_York,[207],NA,US,43.6263,-70.3007,04106,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,04669,STANDARD,True,Prospect Harbor,[Prospect Hbr],[],ME,Hancock County,America/New_York,[207],NA,US,44.4337,-68.0364,04669,1
207,04030,STANDARD,True,East Waterboro,[E Waterboro],[],ME,York County,America/New_York,[207],NA,US,43.5869,-70.7026,04030,1
208,04937,STANDARD,True,Fairfield,[],[],ME,Somerset County,America/New_York,[207],NA,US,44.6675,-69.6795,04937,1
209,04342,STANDARD,True,Dresden,[],[],ME,Lincoln County,America/New_York,[207],NA,US,44.0766,-69.7401,04342,1
210,03902,STANDARD,True,Cape Neddick,[],[],ME,York County,America/New_York,[207],NA,US,43.2225,-70.6402,03902,1

In [151]:
#Combine zip codes within the same city limits and adding the number of reservations together
test_reserv_count = merge_df.groupby(['city','state'], as_index=False)['#_of_reservations'].sum()

In [152]:
#add new column with Maine as the state to measure
test_reserv_count['State'] = 'Maine'

In [153]:
# test to see if the number  of reservations summed equals that of Portland when measured individually
merge_df.loc[merge_df['city'] == 'Portland']

,zip_code,zip_code_type,active,city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,lat,long,zip,#_of_reservations
0,04103,STANDARD,True,Portland,[],[],ME,Cumberland County,America/New_York,[207],NA,US,43.6937,-70.2904,04103,50
6,04101,STANDARD,True,Portland,[],[],ME,Cumberland County,America/New_York,[207],NA,US,43.6608,-70.2613,04101,25
9,04102,STANDARD,True,Portland,[],[],ME,Cumberland County,America/New_York,[207],NA,US,43.6635,-70.3026,04102,21

In [154]:
#test to see if the number of reservations matches the sum for a city like portland
test_reserv_count.sort_values(by='#_of_reservations')

               city state  #_of_reservations  State
0             Abbot    ME                  1  Maine
59      Farmingdale    ME                  1  Maine
145         Roxbury    ME                  1  Maine
57        Fairfield    ME                  1  Maine
56           Exeter    ME                  1  Maine
..              ...   ...                ...    ...
160  South Portland    ME                 28  Maine
6            Auburn    ME                 30  Maine
35   Cape Elizabeth    ME                 30  Maine
29        Brunswick    ME                 31  Maine
137        Portland    ME                 96  Maine

[193 rows x 4 columns]

In [155]:
test_reserv_count.to_csv('Maine_reservations_by_city.csv')

In [301]:
#list=['04101','04102','04103','04104', '04108','04109', '04112', '04116', '04122','04123','04124']
#for x in list:
    #pprint(zipcodes.matching(x))