In [6]:
cd Dirty_data_sets

C:\Users\alexp\OneDrive - University of New Brunswick\Grad Studies\Modelling_transport_pathways\Dirty_data_sets

## Clean data up by removing unnecessary columns and excess words in the city andtown names

In [92]:
import pandas as pd

In [93]:
# Import US city population data from the US on the Census website using the data from:https://www.census.gov/data/tables/time-series/demo/popest/2010s-total-cities-and-towns.html#ds
US_df = pd.read_csv('US_city_population.csv')

In [94]:
US_df

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,...,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,40,1,0,0,0,0,0,A,Alabama,Alabama,...,4785437,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185
1,162,1,0,124,0,0,0,A,Abbeville city,Alabama,...,2699,2694,2643,2628,2608,2600,2584,2575,2571,2560
2,162,1,0,460,0,0,0,A,Adamsville city,Alabama,...,4500,4493,4471,4449,4420,4390,4356,4327,4308,4281
3,162,1,0,484,0,0,0,A,Addison town,Alabama,...,751,750,743,742,739,734,731,726,723,718
4,162,1,0,676,0,0,0,A,Akron town,Alabama,...,355,347,347,343,338,339,333,332,331,328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81429,157,56,43,99990,0,0,1,F,Balance of Washakie County,Wyoming,...,2782,2755,2734,2737,2690,2690,2650,2599,2554,2531
81430,50,56,45,0,0,0,0,A,Weston County,Wyoming,...,7198,7142,7077,7136,7138,7208,7220,6968,6924,6927
81431,157,56,45,56215,0,0,1,A,Newcastle city,Wyoming,...,3530,3506,3476,3483,3484,3513,3530,3409,3394,3397
81432,157,56,45,79125,0,0,1,A,Upton town,Wyoming,...,1098,1089,1081,1088,1095,1104,1105,1062,1057,1056
81433,157,56,45,99990,0,0,1,F,Balance of Weston County,Wyoming,...,2570,2547,2520,2565,2559,2591,2585,2497,2473,2474

In [95]:
#keep only the city/town name, state name, and the population estimate in 2019
US_df = US_df[['NAME','STNAME','POPESTIMATE2019']]

In [96]:
#Remove the word city and town from the end of the place name and remove the spaces at the end of the doucuments
NAME_short= US_df['NAME'].str.rstrip('city').str.rstrip('town').str.rstrip()

In [97]:
#convert it to a list because otherwise it's in some weird format
NAME_list=[]
for name in NAME_short:
    x=name
    NAME_list.append(x)

In [98]:
#readd the city name into the dataframe
US_df['Name'] = NAME_list

<ipython-input-98-adc1e8e2ac6d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  US_df['Name'] = NAME_list

In [99]:
US_df.drop(columns=['NAME'])

        STNAME  POPESTIMATE2019                     Name
0      Alabama          4903185                  Alabama
1      Alabama             2560                Abbeville
2      Alabama             4281               Adamsville
3      Alabama              718                  Addison
4      Alabama              328                    Akron
...        ...              ...                      ...
81429  Wyoming             2531  Balance of Washakie Cou
81430  Wyoming             6927               Weston Cou
81431  Wyoming             3397                Newcastle
81432  Wyoming             1056                    Upton
81433  Wyoming             2474    Balance of Weston Cou

[81434 rows x 3 columns]

In [100]:
US_df.loc[US_df['Name'] == 'Abbot']

             NAME STNAME  POPESTIMATE2019   Name
27337  Abbot town  Maine              677  Abbot

In [101]:
US_df= US_df[['Name','STNAME','POPESTIMATE2019']]

In [102]:
US_df

                          Name   STNAME  POPESTIMATE2019
0                      Alabama  Alabama          4903185
1                    Abbeville  Alabama             2560
2                   Adamsville  Alabama             4281
3                      Addison  Alabama              718
4                        Akron  Alabama              328
...                        ...      ...              ...
81429  Balance of Washakie Cou  Wyoming             2531
81430               Weston Cou  Wyoming             6927
81431                Newcastle  Wyoming             3397
81432                    Upton  Wyoming             1056
81433    Balance of Weston Cou  Wyoming             2474

[81434 rows x 3 columns]

In [103]:
# Drop place names that have duplicated names
US_df = US_df.drop_duplicates(subset=['Name','STNAME'])

In [1]:
US_df.loc[US_df['STNAME'] == 'New Hampshire']

NameError: name 'US_df' is not defined

In [105]:
US_df.to_csv('US_city_pop_clean.csv')

In [106]:
US_df.loc[US_df['Name'] == 'Albion']

         Name      STNAME  POPESTIMATE2019
7462   Albion       Idaho              276
7960   Albion    Illinois             1899
15322  Albion     Indiana             2373
19120  Albion        Iowa              490
27340  Albion       Maine             2094
28881  Albion    Michigan             8402
41965  Albion    Nebraska             1585
48591  Albion    New York             7982
59504  Albion    Oklahoma              100
75981  Albion  Washington              604
78394  Albion   Wisconsin             2093