In [238]:
cd Dirty_data_sets

[WinError 2] The system cannot find the file specified: 'Dirty_data_sets'
C:\Users\alexp\OneDrive - University of New Brunswick\Grad Studies\Modelling_transport_pathways\Dirty_data_sets

In [268]:
import pandas as pd

In [269]:
Reservation_df=pd.read_csv('FY20_Historical_Reservations_Full.csv')

C:\Users\alexp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (5,6,7,12,13,15,17,35) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [270]:
Reservation_df

,historicalreservationid,ordernumber,agency,orgid,codehierarchy,regioncode,regiondescription,parentlocationid,parentlocation,legacyfacilityid,...,totalbeforetax,discount,totalpaid,startdate,enddate,orderdate,nights,numberofpeople,equipmentdescription,equipmentlength
0,fa50401c-f08a-4738-b576-56335cc19cb7,0121072064-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2019-10-17 0:00,2019-10-18 0:00,25:42.3,1 day,6.0,NaN,0.0
1,09c37303-cf15-49d9-9b0c-ccc120328bbb,0200063847-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2020-04-11 0:00,2020-04-12 0:00,35:11.6,1 day,1.0,NaN,0.0
2,f1f5c841-46b1-4ff8-a6dc-fcac2e76ae1c,0200087454-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,83.0,0.0,83.0,2020-09-07 0:00,2020-09-10 0:00,19:08.2,3 days,2.0,NaN,0.0
3,619f4394-1cac-4a64-8f0c-eae6e7f6bf3b,0200102788-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2020-03-21 0:00,2020-03-22 0:00,01:33.9,1 day,3.0,NaN,0.0
4,82674243-7f31-41e6-b3db-d0690513cad3,0200147542-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,0.0,0.0,0.0,2019-12-07 0:00,2019-12-08 0:00,54:01.4,1 day,2.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,e9f6b2b9-a3b0-11ea-b556-6653b7d9f46e,0281991828-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,27.0,0.0,27.0,2020-06-05 0:00,2020-06-05 0:00,40:18.2,0:00:00,1.0,NaN,NaN
1048571,c51c645c-b250-11ea-a96c-8e3940941329,0281991863-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-06-19 0:00,2020-06-19 0:00,20:27.5,0:00:00,1.0,NaN,NaN
1048572,a87f5276-a0ec-11ea-94cc-3aca2611a872,0281991891-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-06-16 0:00,2020-06-16 0:00,09:05.7,0:00:00,1.0,NaN,NaN
1048573,5384e1dc-fd0c-11ea-b504-e2de83ef30d6,0281991986-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-09-30 0:00,2020-09-30 0:00,46:57.7,0:00:00,0.0,NaN,NaN
1048574,35c31b69-c84f-11ea-a856-2a7dac6c22ec,0281992247-1,NPS,128,|1|70904|74324|300013,RMR,Intermountain Region,74291,Rocky Mountain National Park,NaN,...,2.0,0.0,2.0,2020-08-07 0:00,2020-08-07 0:00,02:48.7,0:00:00,0.0,NaN,NaN

In [271]:
Maine_df = Reservation_df.loc[Reservation_df['facilitystate'] == 'Maine']

In [272]:
Maine_df = Maine_df.loc[Maine_df['inventorytype'] == 'CAMPING']

In [273]:
Maine_df.to_csv('Maine_reservations.csv')

In [274]:
Maine_origin_df = Reservation_df.loc[Reservation_df['customerstate'] == 'ME']

In [275]:
Maine_origin_df = Maine_origin_df.loc[Maine_origin_df['inventorytype'] == 'CAMPING']

In [276]:
Maine_origin_df.to_csv('origin_state.csv')

In [277]:
test_df = Maine_origin_df['customerzip'].value_counts()

In [278]:
sum_df = Maine_origin_df['customerzip'].value_counts().rename_axis('zip').reset_index(name='counts')

In [279]:
sum_df

      zip  counts
0    4103      50
1    4011      31
2    4210      30
3    4107      30
4    4106      28
..    ...     ...
206  4952       1
207  4050       1
208  4441       1
209  4935       1
210  4426       1

[211 rows x 2 columns]

In [280]:
sum_list=[]
for x in sum_df['zip']:
    bingo= '0'+ x
    sum_list.append(bingo)

In [281]:
sum_df['zip']= sum_list

In [282]:
test_df = test_df.index.tolist()

In [283]:
Test_list=[]
for x in test_df:
    bongo='0'+ x
    Test_list.append(bongo)

In [284]:
Maine_test_zip=[]
import zipcodes
for x in Test_list:
    Maine_test_zip.append(zipcodes.matching(x))

In [285]:
flattened = [] 
for sublist in Maine_test_zip: 
    for val in sublist: 
        flattened.append(val)

In [286]:
df= pd.DataFrame(flattened,columns=('zip_code','zip_code_type','active','city','acceptable_cities','unacceptable_cities','state','county','timezone','area_codes','world_region','country','lat','long'))

In [287]:
df.drop(columns=['timezone','world_region','country'])

,zip_code,zip_code_type,active,city,acceptable_cities,unacceptable_cities,state,county,area_codes,lat,long
0,04103,STANDARD,True,Portland,[],[],ME,Cumberland County,[207],43.6937,-70.2904
1,04011,STANDARD,True,Brunswick,"[Birch Island, Cundys Harbor, Mere Point]",[Nas Brunswick],ME,Cumberland County,[207],43.8931,-69.9723
2,04210,STANDARD,True,Auburn,[],[],ME,Androscoggin County,[207],44.0862,-70.2272
3,04107,STANDARD,True,Cape Elizabeth,"[Cape Cottage, Cape Eliz, Pond Cove, Portland]",[],ME,Cumberland County,[207],43.5933,-70.2387
4,04106,STANDARD,True,South Portland,"[Portland, S Portland]",[So Portland],ME,Cumberland County,[207],43.6263,-70.3007
...,...,...,...,...,...,...,...,...,...,...,...
206,04952,STANDARD,True,Morrill,[Belmont],[],ME,Waldo County,[207],44.4044,-69.1570
207,04050,STANDARD,True,Long Island,[],[],ME,Cumberland County,[207],43.6913,-70.1536
208,04441,STANDARD,True,Greenville,"[Beaver Cove, Frenchtown Twp, Frenchtwn Twp, L...",[],ME,Piscataquis County,[207],45.5335,-69.4665
209,04935,PO BOX,True,East Vassalboro,[E Vassalboro],[],ME,Kennebec County,[207],44.4478,-69.6066
210,04426,STANDARD,True,Dover Foxcroft,"[Atkinson, Bowerbank, Dovr Foxcroft, Dvr Foxcr...",[],ME,Piscataquis County,[207],45.2386,-69.2048

In [288]:
merge_df=pd.merge(left=df, right=sum_df, left_on='zip_code', right_on='zip')

In [289]:
merge_df = merge_df[merge_df.zip_code_type == 'STANDARD']

In [290]:
merge_df

,zip_code,zip_code_type,active,city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,lat,long,zip,counts
0,04103,STANDARD,True,Portland,[],[],ME,Cumberland County,America/New_York,[207],NA,US,43.6937,-70.2904,04103,50
1,04011,STANDARD,True,Brunswick,"[Birch Island, Cundys Harbor, Mere Point]",[Nas Brunswick],ME,Cumberland County,America/New_York,[207],NA,US,43.8931,-69.9723,04011,31
2,04210,STANDARD,True,Auburn,[],[],ME,Androscoggin County,America/New_York,[207],NA,US,44.0862,-70.2272,04210,30
3,04107,STANDARD,True,Cape Elizabeth,"[Cape Cottage, Cape Eliz, Pond Cove, Portland]",[],ME,Cumberland County,America/New_York,[207],NA,US,43.5933,-70.2387,04107,30
4,04106,STANDARD,True,South Portland,"[Portland, S Portland]",[So Portland],ME,Cumberland County,America/New_York,[207],NA,US,43.6263,-70.3007,04106,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,04553,STANDARD,True,Newcastle,[],[],ME,Lincoln County,America/New_York,[207],NA,US,44.0491,-69.5643,04553,1
206,04952,STANDARD,True,Morrill,[Belmont],[],ME,Waldo County,America/New_York,[207],NA,US,44.4044,-69.1570,04952,1
207,04050,STANDARD,True,Long Island,[],[],ME,Cumberland County,America/New_York,[207],NA,US,43.6913,-70.1536,04050,1
208,04441,STANDARD,True,Greenville,"[Beaver Cove, Frenchtown Twp, Frenchtwn Twp, L...",[],ME,Piscataquis County,America/New_York,[207],NA,US,45.5335,-69.4665,04441,1
210,04426,STANDARD,True,Dover Foxcroft,"[Atkinson, Bowerbank, Dovr Foxcroft, Dvr Foxcr...",[],ME,Piscataquis County,America/New_York,[207],NA,US,45.2386,-69.2048,04426,1

test_reserv_count = merge_df.groupby(['city']).sum()

In [291]:
test_reserv_count

In [237]:
test_reserv_count.to_csv('test_reserv_count.csv')

In [119]:
list=['04101','04102','04103','04104', '04108','04109', '04112', '04116', '04122','04123','04124']
for x in list:
    pprint(zipcodes.matching(x))

[{'acceptable_cities': [],
  'active': True,
  'area_codes': ['207'],
  'city': 'Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6608',
  'long': '-70.2613',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': [],
  'world_region': 'NA',
  'zip_code': '04101',
  'zip_code_type': 'STANDARD'}]
[{'acceptable_cities': [],
  'active': True,
  'area_codes': ['207'],
  'city': 'Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6635',
  'long': '-70.3026',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': [],
  'world_region': 'NA',
  'zip_code': '04102',
  'zip_code_type': 'STANDARD'}]
[{'acceptable_cities': [],
  'active': True,
  'area_codes': ['207'],
  'city': 'Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6937',
  'long': '-70.2904',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': [],
  'world_region': 'NA',
  'zip_code': '04103',
  'zip_code_type': 'STANDARD'}]
[{'acceptable_cities': [],
  'active': True,
  'area_codes': ['207'],
  'city': 'Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6615',
  'long': '-70.2555',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': [],
  'world_region': 'NA',
  'zip_code': '04104',
  'zip_code_type': 'PO BOX'}]
[{'acceptable_cities': ['Portland'],
  'active': True,
  'area_codes': ['207'],
  'city': 'Peaks Island',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6697',
  'long': '-70.1912',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': [],
  'world_region': 'NA',
  'zip_code': '04108',
  'zip_code_type': 'STANDARD'}]
[{'acceptable_cities': ['Cushing Is',
                        'Cushing Island',
                        'Diamond Cove',
                        'Diamond Is',
                        'Diamond Island',
                        'Great Diamond Island',
                        'Grt Dia Is',
                        'Little Diamond Island',
                        'Ltle Dia Is'],
  'active': True,
  'area_codes': ['207'],
  'city': 'Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6530',
  'long': '-70.2016',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': [],
  'world_region': 'NA',
  'zip_code': '04109',
  'zip_code_type': 'STANDARD'}]
[{'acceptable_cities': [],
  'active': True,
  'area_codes': ['207'],
  'city': 'Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6615',
  'long': '-70.2555',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': [],
  'world_region': 'NA',
  'zip_code': '04112',
  'zip_code_type': 'PO BOX'}]
[{'acceptable_cities': ['Portland', 'S Portland'],
  'active': True,
  'area_codes': ['207'],
  'city': 'South Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6615',
  'long': '-70.2555',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': [],
  'world_region': 'NA',
  'zip_code': '04116',
  'zip_code_type': 'PO BOX'}]
[{'acceptable_cities': [],
  'active': True,
  'area_codes': ['207'],
  'city': 'Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6615',
  'long': '-70.2555',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': ['Union Mutual Life Ins'],
  'world_region': 'NA',
  'zip_code': '04122',
  'zip_code_type': 'UNIQUE'}]
[{'acceptable_cities': [],
  'active': True,
  'area_codes': ['207'],
  'city': 'Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6615',
  'long': '-70.2555',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': ['Union Mutual Life Ins'],
  'world_region': 'NA',
  'zip_code': '04123',
  'zip_code_type': 'UNIQUE'}]
[{'acceptable_cities': [],
  'active': True,
  'area_codes': ['207'],
  'city': 'Portland',
  'country': 'US',
  'county': 'Cumberland County',
  'lat': '43.6615',
  'long': '-70.2555',
  'state': 'ME',
  'timezone': 'America/New_York',
  'unacceptable_cities': ['Union Mutual Life Ins'],
  'world_region': 'NA',
  'zip_code': '04124',
  'zip_code_type': 'UNIQUE'}]